# Generated by Django 2.1.3 on 2018-11-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alcaldias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosResidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea1', models.CharField(max_length=100, verbose_name='Direccion 1')),
                ('linea2', models.CharField(max_length=100, verbose_name='Direccion 2')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alcaldias.Municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'DatosResidencia',
                'verbose_name_plural': 'DatosResidencias',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreInstitucion', models.CharField(max_length=200, verbose_name='Institucion')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePais', models.CharField(max_length=100, verbose_name='Pais')),
                ('codigoPais', models.CharField(max_length=10, unique=True, verbose_name='Codigo Pais')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerNombre', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('segundoNombre', models.CharField(max_length=50, verbose_name='Segundo Nombre')),
                ('primerApellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundoApellido', models.CharField(max_length=50, verbose_name='Segundo Apellido')),
                ('dui', models.IntegerField(verbose_name='DUI')),
                ('nit', models.IntegerField(verbose_name='NIT')),
                ('fechaNacimiento', models.DateField(verbose_name='Nacimiento')),
                ('fechaRegistro', models.DateField(auto_now_add=True, verbose_name='Registro')),
                ('tipoPersona', models.IntegerField(verbose_name='Tipo de Persona')),
                ('genero', models.IntegerField(verbose_name='Genero')),
                ('telefonoCasa', models.IntegerField(verbose_name='Telefono Casa')),
                ('celular', models.IntegerField(verbose_name='Telefono Movil')),
                ('nivelEducativo', models.IntegerField(verbose_name='Nivel Educativo')),
                ('ocupacion', models.CharField(max_length=100, verbose_name='Ocupacion')),
                ('contacto', models.IntegerField(verbose_name='Contactar a')),
                ('firma', models.ImageField(upload_to=None, verbose_name='Firma')),
                ('datosResidencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.DatosResidencia', verbose_name='Datos de Residencia')),
                ('institucion', models.ManyToManyField(to='Usuarios.Institucion', verbose_name='Institucion')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Pais', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
