# Generated by Django 2.1.3 on 2018-11-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20181129_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dui',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='DUI'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nit',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='NIT'),
        ),
    ]
