# Generated by Django 2.1.3 on 2018-11-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_auto_20181130_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipoPersona',
            field=models.CharField(blank=True, choices=[('N', 'Natural'), ('J', 'Juridica')], max_length=1, null=True, verbose_name='Tipo de Persona'),
        ),
    ]
