# Generated by Django 2.1.3 on 2018-12-11 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuarios', '0006_auto_20181130_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nombreCompleto',
            field=models.CharField(default=None, max_length=200, verbose_name='Nombre Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Pais', verbose_name='Nacionalidad'),
        ),
    ]
