# Generated by Django 2.1.3 on 2018-12-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_auto_20181210_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombreCompleto',
            new_name='nombre_Completo',
        ),
    ]
