# Generated by Django 2.1.3 on 2018-12-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_auto_20181210_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='documentoFoto',
            field=models.ImageField(blank=True, null=True, upload_to='../static/documentos', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='../static/firmas', verbose_name='Firma'),
        ),
    ]
