# Generated by Django 2.1.3 on 2019-01-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_auto_20181227_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='documentoFoto',
            new_name='documentoFotoAnterior',
        ),
        migrations.AddField(
            model_name='persona',
            name='documentoFotoPosterior',
            field=models.ImageField(blank=True, null=True, upload_to='../static/documentos', verbose_name='Documento'),
        ),
    ]
