# Generated by Django 2.1.3 on 2019-01-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_auto_20190106_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='documentoFotoAnterior',
            field=models.ImageField(blank=True, null=True, upload_to='documentos', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='documentoFotoPosterior',
            field=models.ImageField(blank=True, null=True, upload_to='documentos', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas', verbose_name='Firma'),
        ),
    ]
