# Generated by Django 2.1.3 on 2018-11-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmaSolicitante', models.ImageField(upload_to=None, verbose_name='Firma')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'DetalleSolicitud',
                'verbose_name_plural': 'DetalleSolicitudes',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.IntegerField(verbose_name='Progreso de Solicitud')),
                ('nombreEtapa', models.CharField(max_length=50, verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=50, verbose_name='Categoria')),
                ('detalle', models.TextField(verbose_name='Lo que solicita')),
                ('detalleSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.DetalleSolicitud')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Apertura De Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fechaModificacion',
            field=models.DateField(auto_now=True, null=True, verbose_name='Ultima Modificacion'),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='etapa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.Etapa'),
        ),
    ]
