# Generated by Django 2.1.3 on 2018-11-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0002_auto_20181111_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default=None, max_length=100, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='etapa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.Etapa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, default=None, verbose_name='Apertura De Solicitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fechaModificacion',
            field=models.DateField(auto_now=True, default=None, verbose_name='Ultima Modificacion'),
            preserve_default=False,
        ),
    ]
