# Generated by Django 2.1.3 on 2018-11-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Alcaldias', '0001_initial'),
        ('Solicitudes', '0003_auto_20181111_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesolicitud',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='detallesolicitud',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='detalleSolicitud',
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='alcaldia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alcaldias.Alcaldia', verbose_name='Alcaldia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Persona', verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='requerimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.Requerimiento', verbose_name='Requerimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='detalleSolicitud',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.DetalleSolicitud', verbose_name='Detalle Solicitud'),
            preserve_default=False,
        ),
    ]
