# Generated by Django 2.1.3 on 2018-11-29 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alcaldias', '0001_initial'),
        ('Solicitudes', '0006_remove_solicitud_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesolicitud',
            name='alcaldia',
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='alcaldia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alcaldias.Alcaldia', verbose_name='Alcaldia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='requerimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.Requerimiento', verbose_name='Requerimiento'),
        ),
    ]
