# Generated by Django 2.1.3 on 2018-11-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0009_auto_20181129_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='Solicitante',
            new_name='solicitante',
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='nombreSolicitante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Solicitante'),
        ),
    ]
