# Generated by Django 2.1.3 on 2018-12-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0011_auto_20181215_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallesolicitud',
            old_name='duiSolicitante',
            new_name='documentoSolicitante',
        ),
    ]
