# Generated by Django 2.1.3 on 2019-03-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0013_auto_20190112_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='etapa',
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.Etapa', verbose_name='Etapa'),
        ),
    ]
