# Generated by Django 2.1.3 on 2019-03-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0014_auto_20190315_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='resume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
