# Generated by Django 2.1.3 on 2019-03-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0015_requerimiento_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fechaRespuesta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Respuesta'),
        ),
    ]
