# Generated by Django 2.1.3 on 2019-02-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alcaldias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcaldia',
            name='oficial',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
    ]
